apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-agent-config
data:
  ENVIRONMENT: "production"
  AWS_REGION: "us-east-1"
  BEDROCK_MODEL_ID: "us.anthropic.claude-haiku-4-5-20251001-v1:0"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  API_URL: "http://stock-agent-api-service:8000"
